[build]
builder = "nixpacks"

[deploy]
startCommand = "node src/api/routes.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = "3003" 